/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectotbd2;

/**
 *
 * @author Machado
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear_jugador = new javax.swing.JDialog();
        id_crear_jugador = new javax.swing.JTextField();
        nombre_crear_jugador = new javax.swing.JTextField();
        fechanac_crear_jugador = new javax.swing.JTextField();
        pesobase_crear_jugador = new javax.swing.JTextField();
        pesoextra_crear_jugador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        crear_entrenador = new javax.swing.JDialog();
        fechanac_crear_entrenador = new javax.swing.JTextField();
        pesobase_crear_entrenador = new javax.swing.JTextField();
        pesoextra_crear_entrenador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id_crear_entrenador = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        nombre_crear_entrenador = new javax.swing.JTextField();
        crear_arbitro = new javax.swing.JDialog();
        pesobase_crear_arbitro = new javax.swing.JTextField();
        pesoextra_crear_arbitro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        id_crear_arbitro = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        nombre_crear_arbitro = new javax.swing.JTextField();
        fechanac_crear_arbitro = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Crear = new javax.swing.JMenu();
        jMenuItem_CrearJugador = new javax.swing.JMenuItem();
        jMenuItem_CrearEntrenador = new javax.swing.JMenuItem();
        jMenuItem_CrearArbitro = new javax.swing.JMenuItem();
        jMenu_Modificar = new javax.swing.JMenu();
        jMenu_Eliminar = new javax.swing.JMenu();
        jMenu_Listar = new javax.swing.JMenu();

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Fecha Nacimiento:");

        jLabel4.setText("Peso base:");

        jLabel5.setText("Peso extra:");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crear_jugadorLayout = new javax.swing.GroupLayout(crear_jugador.getContentPane());
        crear_jugador.getContentPane().setLayout(crear_jugadorLayout);
        crear_jugadorLayout.setHorizontalGroup(
            crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_jugadorLayout.createSequentialGroup()
                .addGroup(crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_jugadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesoextra_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesobase_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechanac_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(crear_jugadorLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton1)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        crear_jugadorLayout.setVerticalGroup(
            crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_jugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechanac_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesobase_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoextra_crear_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jLabel6.setText("ID:");

        jLabel7.setText("Nombre:");

        jLabel8.setText("Fecha Nacimiento:");

        jLabel9.setText("Peso base:");

        jLabel10.setText("Peso extra:");

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crear_entrenadorLayout = new javax.swing.GroupLayout(crear_entrenador.getContentPane());
        crear_entrenador.getContentPane().setLayout(crear_entrenadorLayout);
        crear_entrenadorLayout.setHorizontalGroup(
            crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_entrenadorLayout.createSequentialGroup()
                .addGroup(crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_entrenadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(30, 30, 30)
                        .addGroup(crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesoextra_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesobase_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechanac_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(crear_entrenadorLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton2)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        crear_entrenadorLayout.setVerticalGroup(
            crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_entrenadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechanac_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesobase_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_entrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoextra_crear_entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jLabel11.setText("ID:");

        jLabel12.setText("Nombre:");

        jLabel13.setText("Fecha Nacimiento:");

        jLabel14.setText("Peso base:");

        jLabel15.setText("Peso extra:");

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crear_arbitroLayout = new javax.swing.GroupLayout(crear_arbitro.getContentPane());
        crear_arbitro.getContentPane().setLayout(crear_arbitroLayout);
        crear_arbitroLayout.setHorizontalGroup(
            crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_arbitroLayout.createSequentialGroup()
                .addGroup(crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crear_arbitroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(30, 30, 30)
                        .addGroup(crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesoextra_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesobase_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechanac_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(crear_arbitroLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton3)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        crear_arbitroLayout.setVerticalGroup(
            crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_arbitroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechanac_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesobase_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crear_arbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoextra_crear_arbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu_Crear.setText("Crear");

        jMenuItem_CrearJugador.setText("Jugador");
        jMenuItem_CrearJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CrearJugadorActionPerformed(evt);
            }
        });
        jMenu_Crear.add(jMenuItem_CrearJugador);

        jMenuItem_CrearEntrenador.setText("Entrenador");
        jMenuItem_CrearEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CrearEntrenadorActionPerformed(evt);
            }
        });
        jMenu_Crear.add(jMenuItem_CrearEntrenador);

        jMenuItem_CrearArbitro.setText("Arbitro");
        jMenuItem_CrearArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CrearArbitroActionPerformed(evt);
            }
        });
        jMenu_Crear.add(jMenuItem_CrearArbitro);

        jMenuBar1.add(jMenu_Crear);

        jMenu_Modificar.setText("Modificar");
        jMenuBar1.add(jMenu_Modificar);

        jMenu_Eliminar.setText("Eliminar");
        jMenuBar1.add(jMenu_Eliminar);

        jMenu_Listar.setText("Listar");
        jMenuBar1.add(jMenu_Listar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_CrearJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CrearJugadorActionPerformed
        // TODO add your handling code here:
        crear_jugador.setModal(true);
        crear_jugador.pack();
        crear_jugador.setLocationRelativeTo(this);
        crear_jugador.setVisible(true);        
    }//GEN-LAST:event_jMenuItem_CrearJugadorActionPerformed

    private void jMenuItem_CrearEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CrearEntrenadorActionPerformed
        // TODO add your handling code here:
        crear_entrenador.setModal(true);
        crear_entrenador.pack();
        crear_entrenador.setLocationRelativeTo(this);
        crear_entrenador.setVisible(true); 
    }//GEN-LAST:event_jMenuItem_CrearEntrenadorActionPerformed

    private void jMenuItem_CrearArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CrearArbitroActionPerformed
        // TODO add your handling code here:
        crear_arbitro.setModal(true);
        crear_arbitro.pack();
        crear_arbitro.setLocationRelativeTo(this);
        crear_arbitro.setVisible(true); 
    }//GEN-LAST:event_jMenuItem_CrearArbitroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id,fecha,nombre,pesobase,pesoextra;
        id = id_crear_jugador.getText();
        fecha = fechanac_crear_jugador.getText();
        nombre = nombre_crear_jugador.getText();
        pesobase = pesobase_crear_jugador.getText();
        pesoextra = pesoextra_crear_jugador.getText();
        id_crear_jugador.setText("");
        fechanac_crear_jugador.setText("");
        nombre_crear_jugador.setText("");
        pesobase_crear_jugador.setText("");
        pesoextra_crear_jugador.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id,fecha,nombre,pesobase,pesoextra;
        id = id_crear_entrenador.getText();
        fecha = fechanac_crear_entrenador.getText();
        nombre = nombre_crear_entrenador.getText();
        pesobase = pesobase_crear_entrenador.getText();
        pesoextra = pesoextra_crear_entrenador.getText();
        id_crear_entrenador.setText("");
        fechanac_crear_entrenador.setText("");
        nombre_crear_entrenador.setText("");
        pesobase_crear_entrenador.setText("");
        pesoextra_crear_entrenador.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id,fecha,nombre,pesobase,pesoextra;
        id = id_crear_arbitro.getText();
        fecha = fechanac_crear_arbitro.getText();
        nombre = nombre_crear_arbitro.getText();
        pesobase = pesobase_crear_arbitro.getText();
        pesoextra = pesoextra_crear_arbitro.getText();
        id_crear_arbitro.setText("");
        fechanac_crear_arbitro.setText("");
        nombre_crear_arbitro.setText("");
        pesobase_crear_arbitro.setText("");
        pesoextra_crear_arbitro.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog crear_arbitro;
    private javax.swing.JDialog crear_entrenador;
    private javax.swing.JDialog crear_jugador;
    private javax.swing.JTextField fechanac_crear_arbitro;
    private javax.swing.JTextField fechanac_crear_entrenador;
    private javax.swing.JTextField fechanac_crear_jugador;
    private javax.swing.JTextField id_crear_arbitro;
    private javax.swing.JTextField id_crear_entrenador;
    private javax.swing.JTextField id_crear_jugador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_CrearArbitro;
    private javax.swing.JMenuItem jMenuItem_CrearEntrenador;
    private javax.swing.JMenuItem jMenuItem_CrearJugador;
    private javax.swing.JMenu jMenu_Crear;
    private javax.swing.JMenu jMenu_Eliminar;
    private javax.swing.JMenu jMenu_Listar;
    private javax.swing.JMenu jMenu_Modificar;
    private javax.swing.JTextField nombre_crear_arbitro;
    private javax.swing.JTextField nombre_crear_entrenador;
    private javax.swing.JTextField nombre_crear_jugador;
    private javax.swing.JTextField pesobase_crear_arbitro;
    private javax.swing.JTextField pesobase_crear_entrenador;
    private javax.swing.JTextField pesobase_crear_jugador;
    private javax.swing.JTextField pesoextra_crear_arbitro;
    private javax.swing.JTextField pesoextra_crear_entrenador;
    private javax.swing.JTextField pesoextra_crear_jugador;
    // End of variables declaration//GEN-END:variables
}
